#!/usr/bin/env python3

AD_DNS_NAME = 'FS86.VWF.VWFS-AD' # FQDN of your DC (using just the Domain Name to utilize all DC's)
# If using non-SSL use these
 #AD_LDAP_PORT=389
 #AD_LDAP_URL='ldap://%s:%s' % (AD_DNS_NAME,AD_LDAP_PORT)
# If using SSL use these:
AD_LDAP_PORT=389
#AD_LDAP_URL='ldaps://%s:%s' % (AD_DNS_NAME,AD_LDAP_PORT)
AD_LDAP_URL='ldap://%s:%s' % (AD_DNS_NAME,AD_LDAP_PORT)
AD_SEARCH_DN = 'OU=STD-Users,OU=Users,OU=CN,DC=fs86,DC=vwf,DC=vwfs-ad'
AD_NT4_DOMAIN = 'FS86.VWF.VWFS-AD'
AD_SEARCH_FIELDS = ['mail','givenName','sn','sAMAccountName','memberOf']





from ldap3 import *

def ad_search_by_user_id(rd_AD_SAM, password):

    adFltr= "(&(sAMAccountName=" + rd_AD_SAM  + "))"

    s = Server(AD_DNS_NAME, port = AD_LDAP_PORT, get_info = None)
    c = Connection(s,user="cnvwfs02\\dkx4oih",password=password',auto_bind=AUTO_BIND_NO_TLS, client_strategy =SYNC, check_names=True, read_only=True, authentication=NTLM)
    rst=c.search(
            search_base=AD_SEARCH_DN,
            search_filter=adFltr,
            search_scope=SUBTREE,
            attributes=AD_SEARCH_FIELDS,
            size_limit=0,
            time_limit=30
            )

    print (c.result)
    return str(c.entries[0]['mail']).lower()
    c.unbind()


mail=ad_search_by_user_id('DKX4OIH')
print (mail,"type:",str(type(mail)))

