# Generated by Django 2.0.1 on 2018-01-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy_env',
            name='minion_groups',
        ),
        migrations.RemoveField(
            model_name='deploy_env',
            name='project_name',
        ),
        migrations.AlterField(
            model_name='appenv',
            name='name',
            field=models.CharField(default='INIT', max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='deploy_env',
        ),
    ]
